const SUCCESS_CREATED = 201;
const MONGO_DUPLICATE_KEY_ERROR = 11000;
const OK = 200;
const SALT_ROUNDS = 10;

module.exports = {
  SUCCESS_CREATED,
  MONGO_DUPLICATE_KEY_ERROR,
  OK,
  SALT_ROUNDS,
};
